Repository codefordenver/gsn, pull requests merged in 2019-05, with the labels that each got.

#98 Added id field to StudentSerializer that returns Student primary key
  api/gsn_api/gsndb/serializers.py
Labels: fix, in progress

#76 added current endpoints for students to frontend and fixed some props…
  frontend/src/components/LeftNav.js
  frontend/src/components/Routes.js
  frontend/src/components/layouts/Default.js
  frontend/src/pages/StudentDetail.js
  frontend/src/pages/Students.js
  frontend/src/services/studentServices.js
Labels: frontend, in progress

#96 Program endpoints
  api/gsn_api/gsndb/migrations/0002_auto_20190426_2331.py
  api/gsn_api/gsndb/migrations/0003_auto_20190426_2336.py
  api/gsn_api/gsndb/migrations/0004_auto_20190426_2344.py
  api/gsn_api/gsndb/models.py
  api/gsn_api/gsndb/serializers.py
  api/gsn_api/gsndb/urls.py
  api/gsn_api/gsndb/views.py
Labels: in progress
